sonar.projectKey=Sopra-Steria-Code-Academy_CodeAcademy2026_18057138-f0a0-4832-a25f-656706baa85a
sonar.projectName=Idempotweet

# Source directories
sonar.sources=src

# Test directories
sonar.tests=__tests__

# Coverage reports
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.lcov.reportPaths=coverage/lcov.info

# Exclusions
sonar.exclusions=**/node_modules/**,**/.next/**,**/coverage/**,**/.yarn/**,**/dist/**,**/*.test.ts,**/*.test.tsx

# Test exclusions
sonar.test.exclusions=**/__tests__/**,**/*.test.ts,**/*.test.tsx
